### ISSUE TITLE
Create mission modeling tutorial

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie-docs#48]
Our docs have basic info on how to get started mission modeling. It would be nice to have a targeted tutorial on how to start building a mission model from scratch starting with our [template model](https://github.com/NASA-AMMOS/aerie-mission-model-template). Think the [Svelte tutorial](https://svelte.dev/tutorial/basics) but for mission modeling!

**Comment by ewferg** [comment]
Here are a few comments on the docs from my mission modeling experience as a new user:

[The Package-Info java File](https://nasa-ammos.github.io/aerie-docs/mission-modeling/introduction/#the-package-infojava-file)
- Link to location of package-info.java
- Additional explanation or reference to explain java annotations
- I’d try to explain all of the annotations here briefly and what they mean (@MissionModel, etc.)

[The Mission Model Class](https://nasa-ammos.github.io/aerie-docs/mission-modeling/introduction/#the-mission-model-class)
- Explain that the Mission Model class is instantiated by Aerie when it is loaded. 
- Note the different constructors available to the class (one with startTime, one without)
- Explain the example in more detail (this is setting a discrete resource)
- We should have an example of a daemon task

[Activity Types](https://nasa-ammos.github.io/aerie-docs/mission-modeling/activity-types/introduction/)
- Potentially choose a different example
- What is parameter serialization?
- Do we have custom activity type metadata?

[Parameters](https://nasa-ammos.github.io/aerie-docs/mission-modeling/activity-types/parameters/):
- Intro on how to define a parameter within an activity type
- Probably want to mention the import statements you may need

[Effect Model](https://nasa-ammos.github.io/aerie-docs/mission-modeling/activity-types/effect-model/):
- In exceptions section, can we point to where a modeler might look to see where the uncaught exception occurred? 
- I don’t understand where the computed attributes data goes once returned. These aren’t modeled resources, right?

[Resources](https://nasa-ammos.github.io/aerie-docs/mission-modeling/resources-and-models/)
- This needs the most work. We should provide lots of examples of how to create different types of resources
- Start with basic discrete/real resources and move on to more complicated resources
- Need to talk about clock and how the model can know about time (instead of just milliseconds past start)
- Value mappers will need to be explained here
- I think Sampled resource should expose the time step to make it useful

Other
- We should have an example (or at least a tutorial) that takes you through loading resource files into your jar file (e.g. SPICE kernel example)
- Better understanding of the connection between parameters in activities and parameters elsewhere (@Export?)
- Explanation of contrib and its contents...

**Comment by ewferg** [comment]
While I think there is follow-on work to expand our mission modeling tutorial, we now have one, so I think it is appropriate to close this if you agree @dandelany

**Comment by dandelany** [comment]
👍 closing, thanks!
